### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by WilliamDG** [rogeraabbccdd/Client-Convar-Checker#2]
- warnt the client before the punishment ( 1 convar for number of warning before the punishment and 1 convar for the time between warning)

- check only a specific team (SPEC - T - CT). (Maybe you can use bitwise so it's more easy for you and users to choose what team they need, this is only a hint, i'm new on sourcepawn)

**Comment by rogeraabbccdd** [comment]
Warning systeam has been added in 361e8f01116d38d34aac1c69c197cd84f850e228.
For check specific team cvar, sorry I don't want to add this because it's not fair.
